### ISSUE TITLE
Change package name to org.jboss.fuse.wsdl2rest

### ISSUE THREAD

**Issue by tdiesler** [tdiesler/wsdl2rest#7]

**Comment by chirino** [comment]
org.jboss.fuse.wsdl2rest sounds good to me.

**Comment by tdiesler** [comment]
Hi Hiram,

here is the first wsdl2rest <https://github.com/tdiesler/wsdl2rest/releases/tag/0.5> release. Please give it spin - it should work for simple CXF generated WSDL definitions.

The approach I took is to take simple JAX-WS endpoint definitions for both RPC <https://github.com/tdiesler/wsdl2rest/blob/master/impl/src/test/java/org/jboss/fuse/wsdl2rest/test/rpclit/Address.java> and Document <https://github.com/tdiesler/wsdl2rest/blob/master/impl/src/test/java/org/jboss/fuse/wsdl2rest/test/doclit/Address.java> Literal. I then generate <https://github.com/tdiesler/wsdl2rest/blob/master/impl/pom.xml#L83> the WSDL from it. The tool then consumes that WSDL and generates the corresponding JAX-RS endpoints <https://github.com/tdiesler/wsdl2rest/tree/master/tests/src/test/java/org/jboss/fuse/wsdl2rest/test>.

Both, the JAX-WS and the JAX-RS endpoints are implemented and tested using camel-cxf <https://github.com/tdiesler/wsdl2rest/blob/master/tests/src/test/resources/doclit/doclit-camel-context.xml>.

cheers
— thomas
